### ISSUE TITLE
Can't make multiple requests

### ISSUE THREAD

**Issue by austinfrey** [ahdinosaur/pull-http-server#2]
I have a simple server setup, trying to stream a gzipped file back to the client. I get some data back on the first request, but subsequent requests fail with the error below. I feel this might be due to not closing the initial request? but I'm struggling to find a solution. Any help is appreciated!!

Here's my server code...
```
const path = require('path'),
      gzip = require('zlib').createGzip(),
      pull = require('pull-stream'),
      toPull = require('stream-to-pull-stream'),
      file = require('pull-file'),
      createHttpServer = require('pull-http-server')

const inputFile = path.resolve(__dirname, './big.file'),
      zip = toPull.duplex(gzip)

createHttpServer( function (
   stream
){
    pull(
        file(inputFile),
        zip,
        stream
    )
}).listen(9999, '127.0.0.1')
```
...and here is the error on the second request.
```
/node_modules/pull-stream/sinks/drain.js:22
                throw end
                ^

Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketOnEnd (_http_client.js:345:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by austinfrey** [comment]
so this seems to have something to do with the gzip portion. when removed it works just fine. I used a similar setup to stream the zipped file using `pull-net` but http doesn't seem to like it so much :/

**Comment by ahdinosaur** [comment]
hey @aafrey,

the only thing i can think of is that maybe `zip = toPull.duplex(gzip)` should be `zip = toPull.transform(gzip)`, since it's not being used a duplex stream but instead a transform stream (although i might be wrong about this).

**Comment by austinfrey** [comment]
no luck... Is there a way to manually end the stream? I've played around with `stream.sink.end()` but either I'm not calling it correctly or that isn't the correct way of doing it.
